import '../../core/settings/app_setting_keys.dart';
import '../../core/utils/date_range_utils.dart';
import '../../domain/models/salary_calculation.dart';
import '../../domain/models/salary_slip.dart';
import '../../domain/services/salary_calculation_service.dart';
import '../../domain/services/salary_slip_service.dart';
import 'app_setting_repository.dart';
import 'attendance_repository.dart';
import 'employee_repository.dart';
import 'salary_slip_repository.dart';

class SalarySlipCoordinator {
  SalarySlipCoordinator({
    required SalarySlipRepository salarySlipRepository,
    required EmployeeRepository employeeRepository,
    required AttendanceRepository attendanceRepository,
    required AppSettingRepository settingsRepository,
  })  : _salarySlipRepository = salarySlipRepository,
        _employeeRepository = employeeRepository,
        _attendanceRepository = attendanceRepository,
        _settingsRepository = settingsRepository;

  final SalarySlipRepository _salarySlipRepository;
  final EmployeeRepository _employeeRepository;
  final AttendanceRepository _attendanceRepository;
  final AppSettingRepository _settingsRepository;

  Future<int> getGenerationDay() async {
    final raw = await _settingsRepository.getString(
      AppSettingKeys.salaryGenerationDay,
    );
    final parsed = int.tryParse(raw ?? '');
    return (parsed ?? 1).clamp(1, 28);
  }

  Future<void> setGenerationDay(int day) {
    return _settingsRepository.setString(
      AppSettingKeys.salaryGenerationDay,
      day.clamp(1, 28).toString(),
    );
  }

  Future<SalarySlipGenerationResult> generateDraftSlips({
    required SalaryPeriod period,
    required String generatedByUserId,
    required String deviceId,
    DateTime? generatedAt,
  }) async {
    final calculation = await _calculateFinalPayroll(period);
    final inputs = SalarySlipService.buildDraftInputs(
      calculation: calculation,
      period: period,
    );

    var createdCount = 0;
    var skippedCount = 0;

    for (final input in inputs) {
      final existing = await _salarySlipRepository.findForEmployeePeriod(
        employeeId: input.employeeId,
        periodStart: input.periodStart,
        periodEnd: input.periodEnd,
      );
      if (existing != null) {
        skippedCount += 1;
        continue;
      }

      await _salarySlipRepository.createDraft(
        input: input,
        generatedByUserId: generatedByUserId,
        deviceId: deviceId,
        generatedAt: generatedAt,
      );
      createdCount += 1;
    }

    if (createdCount > 0) {
      await _markAutoGeneratedPeriod(period);
    }

    return SalarySlipGenerationResult(
      period: period,
      createdCount: createdCount,
      skippedCount: skippedCount,
    );
  }

  Future<SalarySlipGenerationResult> generateDraftSlipsForRange({
    required SalesDateRange range,
    required String generatedByUserId,
    required String deviceId,
  }) {
    return generateDraftSlips(
      period: SalarySlipService.periodFromRange(range),
      generatedByUserId: generatedByUserId,
      deviceId: deviceId,
    );
  }

  Future<SalarySlipGenerationResult?> maybeAutoGenerate({
    required String generatedByUserId,
    required String deviceId,
    DateTime? now,
  }) async {
    final anchor = now ?? DateTime.now();
    final generationDay = await getGenerationDay();
    final period = SalarySlipService.priorCalendarMonthPeriod(anchor);
    final periodStart = SalarySlipService.normalizedPeriodStart(period);
    final periodEnd = SalarySlipService.inclusivePeriodEnd(period);

    final alreadyGenerated = await _salarySlipRepository.hasSlipsForPeriod(
      periodStart: periodStart,
      periodEnd: periodEnd,
    );

    final check = SalarySlipService.evaluateAutoGeneration(
      generationDay: generationDay,
      now: anchor,
      priorPeriodAlreadyGenerated: alreadyGenerated,
    );

    if (!check.shouldGenerate) return null;

    return generateDraftSlips(
      period: check.period,
      generatedByUserId: generatedByUserId,
      deviceId: deviceId,
      generatedAt: anchor,
    );
  }

  Future<SalarySlip?> updateDraftDeductions({
    required String slipId,
    required double? deductions,
    required String deviceId,
  }) {
    return _salarySlipRepository.updateDraftDeductions(
      slipId: slipId,
      deductions: deductions,
      deviceId: deviceId,
    );
  }

  Future<SalarySlip?> finalizeSlip({
    required String slipId,
    required String deviceId,
  }) {
    return _salarySlipRepository.finalize(
      slipId: slipId,
      deviceId: deviceId,
    );
  }

  Future<SalaryCalculationResult> _calculateFinalPayroll(
    SalaryPeriod period,
  ) async {
    final employees = await _employeeRepository.findAll();
    final attendanceRecords = await _attendanceRepository.findInRange(
      startInclusive: period.startInclusive,
      endExclusive: period.endExclusive,
    );

    return SalaryCalculationService.calculate(
      period: period,
      mode: SalaryCalculationMode.finalPayroll,
      employees: employees,
      attendanceRecords: attendanceRecords,
    );
  }

  Future<void> _markAutoGeneratedPeriod(SalaryPeriod period) async {
    final periodEnd = SalarySlipService.inclusivePeriodEnd(period);
    await _settingsRepository.setString(
      AppSettingKeys.salaryLastAutoPeriodEnd,
      periodEnd.toIso8601String(),
    );
  }
}
